# Project
version=2.0.0
group=net.yirmiri.dungeonsdelight
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Dungeon's Delight
mod_author=Yirmiri
mod_id=dungeonsdelight
license=AZURUNE License
credits=Betwixer (original artist), Artyrian (additional programmer)
description=Dungeon's Delight is a cooking and farming mod in which you turn monsters into delicious delicacies.
minecraft_version_range=[1.20.1, 1.22)
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Dependencies
forge_runiclib=8188415
fabric_runiclib=8188413

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
