modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "AZURUNE License" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/Yirmiri/Dungeons-Delight/issues" #optional

[[mods]] #mandatory
modId = "dungeonsdelight" #mandatory
version = "1.4.3" #mandatory
displayName = "Dungeon's Delight" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile="icon.png" #optional
#credits="Yirmiri & Betwixer" #optional
authors = "Yirmiri & Betwixer" #optional
description = '''Dungeon's Delight is a Farmer's Delight addon in which you turn monsters into monstrous treats!''' #mandatory (Supports multiline text)

enumExtensions="META-INF/dungeonsdelight_enumextensions.json"

[[mixins]]
config = "dungeonsdelight.mixin.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.dungeonsdelight]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[21.1.133,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.dungeonsdelight]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dungeonsdelight]]
modId = "farmersdelight"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[1.2.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dungeonsdelight]]
modId="runiclib"
type="required"
versionRange="[4.3.7,)"
ordering="AFTER"
side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"