modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory
# The version number of the mod
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="icon.png" #optional
#credits="" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

## Catalogue mod compatibility
## itemIcon = "dungeonsdelight:dungeon_stove"
## configBackground = "dungeonsdelight:textures/block/dungeon_stove_side.png"

[[mixins]]
config = "${mod_id}.mixin.json"

[[dependencies.dungeonsdelight]] #optional
    modId="neoforge" #mandatory
    mandatory=true #mandatory
    versionRange="${neoforge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeonsdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeonsdelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dungeonsdelight]]
modId="runiclib"
mandatory=true
versionRange="[4.1.5,)"
ordering="AFTER"
side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"